var ct_ajaxurl='http://websitesetup.org/wp-admin/admin-ajax.php';var ct_info_flag=false;var ct_set_cookies_flag=true;;window._wpemojiSettings={"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/72x72\/","ext":".png","source":{"wpemoji":"http:\/\/websitesetup.org\/wp-includes\/js\/wp-emoji.js?ver=4.5.2","twemoji":"http:\/\/websitesetup.org\/wp-includes\/js\/twemoji.js?ver=4.5.2"}};(function(window,document,settings){var src,ready,ii,tests;function browserSupportsEmoji(type){var canvas=document.createElement('canvas'),context=canvas.getContext&&canvas.getContext('2d'),stringFromCharCode=String.fromCharCode,tonedata,tone,tone2;if(!context||!context.fillText){return false;}
context.textBaseline='top';context.font='600 32px Arial';switch(type){case'flag':context.fillText(stringFromCharCode(55356,56806,55356,56826),0,0);return canvas.toDataURL().length>3000;case'diversity':context.fillText(stringFromCharCode(55356,57221),0,0);tonedata=context.getImageData(16,16,1,1).data;tone=tonedata[0]+','+tonedata[1]+','+tonedata[2]+','+tonedata[3];context.fillText(stringFromCharCode(55356,57221,55356,57343),0,0);tonedata=context.getImageData(16,16,1,1).data;tone2=tonedata[0]+','+tonedata[1]+','+tonedata[2]+','+tonedata[3];return tone!==tone2;case'simple':context.fillText(stringFromCharCode(55357,56835),0,0);return context.getImageData(16,16,1,1).data[0]!==0;case'unicode8':context.fillText(stringFromCharCode(55356,57135),0,0);return context.getImageData(16,16,1,1).data[0]!==0;}
return false;}
function addScript(src){var script=document.createElement('script');script.src=src;script.type='text/javascript';document.getElementsByTagName('head')[0].appendChild(script);}
tests=Array('simple','flag','unicode8','diversity');settings.supports={everything:true,everythingExceptFlag:true};for(ii=0;ii<tests.length;ii++){settings.supports[tests[ii]]=browserSupportsEmoji(tests[ii]);settings.supports.everything=settings.supports.everything&&settings.supports[tests[ii]];if('flag'!==tests[ii]){settings.supports.everythingExceptFlag=settings.supports.everythingExceptFlag&&settings.supports[tests[ii]];}}
settings.supports.everythingExceptFlag=settings.supports.everythingExceptFlag&&!settings.supports.flag;settings.DOMReady=false;settings.readyCallback=function(){settings.DOMReady=true;};if(!settings.supports.everything){ready=function(){settings.readyCallback();};if(document.addEventListener){document.addEventListener('DOMContentLoaded',ready,false);window.addEventListener('load',ready,false);}else{window.attachEvent('onload',ready);document.attachEvent('onreadystatechange',function(){if('complete'===document.readyState){settings.readyCallback();}});}
src=settings.source||{};if(src.concatemoji){addScript(src.concatemoji);}else if(src.wpemoji&&src.twemoji){addScript(src.twemoji);addScript(src.wpemoji);}}})(window,document,window._wpemojiSettings);function essb_window1357663573(oUrl,oService){essb_window(oUrl,oService,766);};function essb_pinterenst1357663573(){essb_pinterenst();};function expand(e){e.style.display="none"==e.style.display?"block":"none"}function wpex_toggle(e,n,l){el=document.getElementById("wpexlink"+e),el.innerHTML=el.innerHTML==n?l:n,expand(document.getElementById("wpex"+e))};jQuery(document).ready(function($){var kube_social_scripts=function(scripts){$.each(scripts,function(index,script){if($('#'+script.id).length>0)
return false;$('<script/>',{type:'text/javascript',id:script.id,src:script.url}).appendTo('body');});}
kube_social_scripts([{'id':'facebook-jssdk','url':'//connect.facebook.net/en_US/all.js#xfbml=1'},{'id':'twitter-wjs','url':'//platform.twitter.com/widgets.js'},{'id':'google-platform','url':'//apis.google.com/js/platform.js'},]);});var _wpcf7={"loaderUrl":"http:\/\/websitesetup.org\/wp-content\/plugins\/contact-form-7\/images\/ajax-loader.gif","recaptchaEmpty":"Please verify that you are not a robot.","sending":"Sending ..."};var kube={"selector":".kube","preload":"3","effect_prev":"fade","effect_next":"fade","effect_in":"fade","effect_out":"fade","auto_size":"1","width":"800","height":"450","autoplay":"0","playspeed":"3000","social":"1","rel_selector":"lightbox"};(function($){$('a[href*=#]:not([href=#])').click(function(){console.log('clicked');if(location.pathname.replace(/^\//,'')==this.pathname.replace(/^\//,'')||location.hostname==this.hostname)
{var target=$(this.hash),headerHeight=$("#wpadminbar").height()+5;target=target.length?target:$('[name='+this.hash.slice(1)+']');if(target.length)
{$('html,body').animate({scrollTop:target.offset().top-($('#wpadminbar').outerHeight())},500);return false;}}});$(function(){window.setTimeout(function(){$(".front-page .front-banner iframe").contents().find(".e-entry-title").css({"font-size":"14px","line-height":"18px"});},1000);});})(jQuery);